package com.senthil.net;

import com.google.gson.Gson;
import com.senthil.model.Comments;
import com.senthil.model.Diffs;
import com.senthil.model.ReviewFiles;
import com.senthil.model.Repositories;
import com.senthil.model.ReviewRequests;
import java.io.InputStreamReader;


/**
 * Created by spanneer on 2/22/17.
 */
public class Test {

  public static void main(String[] args) {
    testComments();
      testRepositories();
      testReviewRequests();
    testDiff();
    testFiles();
  }

  private static void testFiles() {
    String response = "{\n" + "  \"files\": [\n" + "    {\n" + "      \"dest_attachment\": null, \n"
        + "      \"dest_detail\": \"(working copy)\", \n"
        + "      \"dest_file\": \"/trunk/reviewboard/settings_local.py.tmpl\", \n" + "      \"extra_data\": {\n"
        + "        \"delete_count\": 5, \n" + "        \"equal_count\": 35, \n" + "        \"insert_count\": 4, \n"
        + "        \"orig_sha1\": \"5ab9c202636417016379061749915006efac40a0\", \n"
        + "        \"patched_sha1\": \"2c08ecb7ba61733c2ef794c1fa7e49090a4a334f\", \n"
        + "        \"raw_delete_count\": 5, \n" + "        \"raw_insert_count\": 4, \n"
        + "        \"replace_count\": 0, \n" + "        \"total_line_count\": 44\n" + "      }, \n"
        + "      \"id\": 31, \n" + "      \"links\": {\n" + "        \"diff_comments\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/files/31/diff-comments/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"original_file\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/files/31/original-file/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"patched_file\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/files/31/patched-file/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/files/31/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/files/31/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }\n" + "      }, \n" + "      \"source_attachment\": null, \n"
        + "      \"source_file\": \"/trunk/reviewboard/settings_local.py.tmpl\", \n"
        + "      \"source_revision\": \"1797\"\n" + "    }, \n" + "    {\n" + "      \"dest_attachment\": null, \n"
        + "      \"dest_detail\": \"(revision 0)\", \n" + "      \"dest_file\": \"/trunk/reviewboard/TESTING\", \n"
        + "      \"extra_data\": {}, \n" + "      \"id\": 36, \n" + "      \"links\": {\n"
        + "        \"diff_comments\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/files/36/diff-comments/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"original_file\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/files/36/original-file/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"patched_file\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/files/36/patched-file/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/files/36/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/files/36/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }\n" + "      }, \n" + "      \"source_attachment\": null, \n"
        + "      \"source_file\": \"/trunk/reviewboard/TESTING\", \n" + "      \"source_revision\": \"PRE-CREATION\"\n"
        + "    }\n" + "  ], \n" + "  \"links\": {\n" + "    \"self\": {\n"
        + "      \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/files/\", \n"
        + "      \"method\": \"GET\"\n" + "    }\n" + "  }, \n" + "  \"stat\": \"ok\", \n" + "  \"total_results\": 2\n"
        + "}";

    ReviewFiles collection = new Gson().fromJson(response, ReviewFiles.class);
    System.out.println(collection);
  }

  private static void testDiff() {
    String response = "{\n" + "  \"diffs\": [\n" + "    {\n" + "      \"base_commit_id\": null, \n"
        + "      \"basedir\": \"\", \n" + "      \"extra_data\": {}, \n" + "      \"id\": 8, \n"
        + "      \"links\": {\n" + "        \"files\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/files/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"repository\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"Review Board SVN\"\n" + "        }, \n"
        + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/1/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }\n" + "      }, \n" + "      \"name\": \"diff\", \n"
        + "      \"revision\": 1, \n" + "      \"timestamp\": \"2009-02-25T02:01:21Z\"\n" + "    }, \n" + "    {\n"
        + "      \"base_commit_id\": null, \n" + "      \"basedir\": \"\", \n" + "      \"extra_data\": {}, \n"
        + "      \"id\": 11, \n" + "      \"links\": {\n" + "        \"files\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/3/files/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"repository\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"Review Board SVN\"\n" + "        }, \n"
        + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/3/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/3/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }\n" + "      }, \n" + "      \"name\": \"diff\", \n"
        + "      \"revision\": 3, \n" + "      \"timestamp\": \"2009-02-25T21:39:42Z\"\n" + "    }\n" + "  ], \n"
        + "  \"links\": {\n" + "    \"create\": {\n"
        + "      \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/\", \n"
        + "      \"method\": \"POST\"\n" + "    }, \n" + "    \"self\": {\n"
        + "      \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/\", \n"
        + "      \"method\": \"GET\"\n" + "    }\n" + "  }, \n" + "  \"stat\": \"ok\", \n" + "  \"total_results\": 2\n"
        + "}";
    Diffs diffs = new Gson().fromJson(response, Diffs.class);
    System.out.println(diffs);
  }

  private static void testReviewRequests() {
    String response = "{\n" + "  \"links\": {\n" + "    \"create\": {\n"
        + "      \"href\": \"http://reviews.example.com/api/review-requests/\", \n" + "      \"method\": \"POST\"\n"
        + "    }, \n" + "    \"self\": {\n" + "      \"href\": \"http://reviews.example.com/api/review-requests/\", \n"
        + "      \"method\": \"GET\"\n" + "    }\n" + "  }, \n" + "  \"review_requests\": [\n" + "    {\n"
        + "      \"absolute_url\": \"http://reviews.example.com/r/8/\", \n"
        + "      \"approval_failure\": \"The review request has not been marked \\\"Ship It!\\\"\", \n"
        + "      \"approved\": false, \n" + "      \"blocks\": [], \n" + "      \"branch\": \"trunk\", \n"
        + "      \"bugs_closed\": [], \n" + "      \"changenum\": null, \n" + "      \"close_description\": null, \n"
        + "      \"close_description_text_type\": \"plain\", \n" + "      \"commit_id\": null, \n"
        + "      \"depends_on\": [], \n" + "      \"description\": \"This is a test designed for interdiffs.\", \n"
        + "      \"description_text_type\": \"plain\", \n" + "      \"extra_data\": {}, \n" + "      \"id\": 8, \n"
        + "      \"issue_dropped_count\": 0, \n" + "      \"issue_open_count\": 0, \n"
        + "      \"issue_resolved_count\": 0, \n" + "      \"last_updated\": \"2013-09-07T02:26:18Z\", \n"
        + "      \"links\": {\n" + "        \"changes\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/changes/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"delete\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/\", \n"
        + "          \"method\": \"DELETE\"\n" + "        }, \n" + "        \"diff_context\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diff-context/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"diffs\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"draft\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/draft/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"file_attachments\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/file-attachments/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"last_update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/last-update/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"latest_diff\": {\n"
        + "          \"href\": \"http://example.com/api/review-requests/8/diffs/3/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"repository\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"Review Board SVN\"\n" + "        }, \n"
        + "        \"reviews\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/reviews/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"screenshots\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/screenshots/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"status_updates\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/status-updates/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"submitter\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/users/admin/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"admin\"\n" + "        }, \n"
        + "        \"update\": {\n" + "          \"href\": \"http://reviews.example.com/api/review-requests/8/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }\n" + "      }, \n" + "      \"public\": true, \n"
        + "      \"ship_it_count\": 0, \n" + "      \"status\": \"pending\", \n"
        + "      \"summary\": \"Interdiff Revision Test\", \n" + "      \"target_groups\": [], \n"
        + "      \"target_people\": [\n" + "        {\n"
        + "          \"href\": \"http://reviews.example.com/api/users/grumpy/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"grumpy\"\n" + "        }\n" + "      ], \n"
        + "      \"testing_done\": \"\", \n" + "      \"testing_done_text_type\": \"plain\", \n"
        + "      \"text_type\": null, \n" + "      \"time_added\": \"2013-08-07T02:01:21Z\", \n"
        + "      \"url\": \"/r/8/\"\n" + "    }, \n" + "    {\n"
        + "      \"absolute_url\": \"http://reviews.example.com/r/9/\", \n"
        + "      \"approval_failure\": \"The review request has not been marked \\\"Ship It!\\\"\", \n"
        + "      \"approved\": false, \n" + "      \"blocks\": [], \n" + "      \"branch\": \"\", \n"
        + "      \"bugs_closed\": [], \n" + "      \"changenum\": null, \n" + "      \"close_description\": null, \n"
        + "      \"close_description_text_type\": \"plain\", \n" + "      \"commit_id\": \"\", \n"
        + "      \"depends_on\": [], \n" + "      \"description\": \"Just some tests for diff file attachments\", \n"
        + "      \"description_text_type\": \"plain\", \n" + "      \"extra_data\": {}, \n" + "      \"id\": 9, \n"
        + "      \"issue_dropped_count\": 0, \n" + "      \"issue_open_count\": 0, \n"
        + "      \"issue_resolved_count\": 0, \n" + "      \"last_updated\": \"2013-09-06T20:19:34Z\", \n"
        + "      \"links\": {\n" + "        \"changes\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/9/changes/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"delete\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/9/\", \n"
        + "          \"method\": \"DELETE\"\n" + "        }, \n" + "        \"diff_context\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/9/diff-context/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"diffs\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/9/diffs/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"draft\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/9/draft/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"file_attachments\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/9/file-attachments/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"last_update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/9/last-update/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"latest_diff\": {\n"
        + "          \"href\": \"http://example.com/api/review-requests/9/diffs/1/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"repository\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"Review Board SVN\"\n" + "        }, \n"
        + "        \"reviews\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/9/reviews/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"screenshots\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/9/screenshots/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/9/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"status_updates\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/9/status-updates/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"submitter\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/users/doc/\", \n" + "          \"method\": \"GET\", \n"
        + "          \"title\": \"doc\"\n" + "        }, \n" + "        \"update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/9/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }\n" + "      }, \n" + "      \"public\": true, \n"
        + "      \"ship_it_count\": 0, \n" + "      \"status\": \"pending\", \n"
        + "      \"summary\": \"Diff file attachments test\", \n" + "      \"target_groups\": [\n" + "        {\n"
        + "          \"href\": \"http://reviews.example.com/api/groups/devgroup/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"devgroup\"\n" + "        }\n" + "      ], \n"
        + "      \"target_people\": [], \n" + "      \"testing_done\": \"\", \n"
        + "      \"testing_done_text_type\": \"plain\", \n" + "      \"text_type\": null, \n"
        + "      \"time_added\": \"2013-09-06T19:38:35Z\", \n" + "      \"url\": \"/r/9/\"\n" + "    }, \n" + "    {\n"
        + "      \"absolute_url\": \"http://reviews.example.com/r/4/\", \n"
        + "      \"approval_failure\": \"The review request has not been marked \\\"Ship It!\\\"\", \n"
        + "      \"approved\": false, \n" + "      \"blocks\": [], \n" + "      \"branch\": \"\", \n"
        + "      \"bugs_closed\": [\n" + "        \"12345\"\n" + "      ], \n" + "      \"changenum\": 1234, \n"
        + "      \"close_description\": null, \n" + "      \"close_description_text_type\": \"plain\", \n"
        + "      \"commit_id\": \"1234\", \n" + "      \"depends_on\": [], \n"
        + "      \"description\": \"Test description.\", \n" + "      \"description_text_type\": \"plain\", \n"
        + "      \"extra_data\": {}, \n" + "      \"id\": 4, \n" + "      \"issue_dropped_count\": 0, \n"
        + "      \"issue_open_count\": 0, \n" + "      \"issue_resolved_count\": 0, \n"
        + "      \"last_updated\": \"2007-06-24T01:11:24Z\", \n" + "      \"links\": {\n" + "        \"changes\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/4/changes/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"delete\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/4/\", \n"
        + "          \"method\": \"DELETE\"\n" + "        }, \n" + "        \"diff_context\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/4/diff-context/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"diffs\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/4/diffs/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"draft\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/4/draft/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"file_attachments\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/4/file-attachments/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"last_update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/4/last-update/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"latest_diff\": {\n"
        + "          \"href\": \"http://example.com/api/review-requests/4/diffs/1/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"repository\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"Review Board SVN\"\n" + "        }, \n"
        + "        \"reviews\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/4/reviews/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"screenshots\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/4/screenshots/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/4/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"status_updates\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/4/status-updates/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"submitter\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/users/grumpy/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"grumpy\"\n" + "        }, \n"
        + "        \"update\": {\n" + "          \"href\": \"http://reviews.example.com/api/review-requests/4/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }\n" + "      }, \n" + "      \"public\": true, \n"
        + "      \"ship_it_count\": 0, \n" + "      \"status\": \"pending\", \n"
        + "      \"summary\": \"Made e-mail improvements\", \n" + "      \"target_groups\": [], \n"
        + "      \"target_people\": [\n" + "        {\n"
        + "          \"href\": \"http://reviews.example.com/api/users/doc/\", \n" + "          \"method\": \"GET\", \n"
        + "          \"title\": \"doc\"\n" + "        }\n" + "      ], \n" + "      \"testing_done\": \"Tested.\", \n"
        + "      \"testing_done_text_type\": \"plain\", \n" + "      \"text_type\": null, \n"
        + "      \"time_added\": \"2007-06-24T00:42:42Z\", \n" + "      \"url\": \"/r/4/\"\n" + "    }, \n" + "    {\n"
        + "      \"absolute_url\": \"http://reviews.example.com/r/6/\", \n"
        + "      \"approval_failure\": \"The review request has not been marked \\\"Ship It!\\\"\", \n"
        + "      \"approved\": false, \n" + "      \"blocks\": [], \n" + "      \"branch\": \"trunk\", \n"
        + "      \"bugs_closed\": [], \n" + "      \"changenum\": null, \n" + "      \"close_description\": null, \n"
        + "      \"close_description_text_type\": \"plain\", \n" + "      \"commit_id\": null, \n"
        + "      \"depends_on\": [], \n" + "      \"description\": \"Foo\", \n"
        + "      \"description_text_type\": \"plain\", \n" + "      \"extra_data\": {}, \n" + "      \"id\": 6, \n"
        + "      \"issue_dropped_count\": 0, \n" + "      \"issue_open_count\": 0, \n"
        + "      \"issue_resolved_count\": 0, \n" + "      \"last_updated\": \"2007-06-24T01:10:59Z\", \n"
        + "      \"links\": {\n" + "        \"changes\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/6/changes/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"delete\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/6/\", \n"
        + "          \"method\": \"DELETE\"\n" + "        }, \n" + "        \"diff_context\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/6/diff-context/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"diffs\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/6/diffs/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"draft\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/6/draft/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"file_attachments\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/6/file-attachments/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"last_update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/6/last-update/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"latest_diff\": {\n"
        + "          \"href\": \"http://example.com/api/review-requests/6/diffs/1/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"repository\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"Review Board SVN\"\n" + "        }, \n"
        + "        \"reviews\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/6/reviews/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"screenshots\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/6/screenshots/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/6/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"status_updates\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/6/status-updates/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"submitter\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/users/dopey/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"dopey\"\n" + "        }, \n"
        + "        \"update\": {\n" + "          \"href\": \"http://reviews.example.com/api/review-requests/6/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }\n" + "      }, \n" + "      \"public\": true, \n"
        + "      \"ship_it_count\": 0, \n" + "      \"status\": \"pending\", \n"
        + "      \"summary\": \"Error dialog\", \n" + "      \"target_groups\": [\n" + "        {\n"
        + "          \"href\": \"http://reviews.example.com/api/groups/emptygroup/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"emptygroup\"\n" + "        }\n" + "      ], \n"
        + "      \"target_people\": [], \n" + "      \"testing_done\": \"Bar\", \n"
        + "      \"testing_done_text_type\": \"plain\", \n" + "      \"text_type\": null, \n"
        + "      \"time_added\": \"2007-06-24T00:47:14Z\", \n" + "      \"url\": \"/r/6/\"\n" + "    }, \n" + "    {\n"
        + "      \"absolute_url\": \"http://reviews.example.com/r/2/\", \n"
        + "      \"approval_failure\": \"The review request has not been marked \\\"Ship It!\\\"\", \n"
        + "      \"approved\": false, \n" + "      \"blocks\": [], \n" + "      \"branch\": \"trunk\", \n"
        + "      \"bugs_closed\": [\n" + "        \"123\"\n" + "      ], \n" + "      \"changenum\": null, \n"
        + "      \"close_description\": null, \n" + "      \"close_description_text_type\": \"plain\", \n"
        + "      \"commit_id\": null, \n" + "      \"depends_on\": [], \n"
        + "      \"description\": \"Be compatible with cleaned_data changes in Django.\", \n"
        + "      \"description_text_type\": \"plain\", \n" + "      \"extra_data\": {}, \n" + "      \"id\": 2, \n"
        + "      \"issue_dropped_count\": 0, \n" + "      \"issue_open_count\": 0, \n"
        + "      \"issue_resolved_count\": 0, \n" + "      \"last_updated\": \"2007-06-24T00:34:17Z\", \n"
        + "      \"links\": {\n" + "        \"changes\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/2/changes/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"delete\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/2/\", \n"
        + "          \"method\": \"DELETE\"\n" + "        }, \n" + "        \"diff_context\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/2/diff-context/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"diffs\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/2/diffs/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"draft\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/2/draft/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"file_attachments\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/2/file-attachments/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"last_update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/2/last-update/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"latest_diff\": {\n"
        + "          \"href\": \"http://example.com/api/review-requests/2/diffs/1/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"repository\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"Review Board SVN\"\n" + "        }, \n"
        + "        \"reviews\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/2/reviews/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"screenshots\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/2/screenshots/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/2/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"status_updates\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/2/status-updates/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"submitter\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/users/dopey/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"dopey\"\n" + "        }, \n"
        + "        \"update\": {\n" + "          \"href\": \"http://reviews.example.com/api/review-requests/2/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }\n" + "      }, \n" + "      \"public\": true, \n"
        + "      \"ship_it_count\": 0, \n" + "      \"status\": \"pending\", \n"
        + "      \"summary\": \"Update for cleaned_data changes\", \n" + "      \"target_groups\": [\n" + "        {\n"
        + "          \"href\": \"http://reviews.example.com/api/groups/devgroup/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"devgroup\"\n" + "        }\n" + "      ], \n"
        + "      \"target_people\": [], \n" + "      \"testing_done\": \"Works.\", \n"
        + "      \"testing_done_text_type\": \"plain\", \n" + "      \"text_type\": null, \n"
        + "      \"time_added\": \"2007-06-24T00:14:32Z\", \n" + "      \"url\": \"/r/2/\"\n" + "    }, \n" + "    {\n"
        + "      \"absolute_url\": \"http://reviews.example.com/r/3/\", \n"
        + "      \"approval_failure\": \"The review request has not been marked \\\"Ship It!\\\"\", \n"
        + "      \"approved\": false, \n" + "      \"blocks\": [], \n" + "      \"branch\": \"trunk\", \n"
        + "      \"bugs_closed\": [\n" + "        \"1234\", \n" + "        \"4321\", \n" + "        \"5678\", \n"
        + "        \"8765\"\n" + "      ], \n" + "      \"changenum\": null, \n"
        + "      \"close_description\": null, \n" + "      \"close_description_text_type\": \"plain\", \n"
        + "      \"commit_id\": null, \n" + "      \"depends_on\": [], \n"
        + "      \"description\": \"Added some user permissions checking for JSON API functions.\", \n"
        + "      \"description_text_type\": \"plain\", \n" + "      \"extra_data\": {}, \n" + "      \"id\": 3, \n"
        + "      \"issue_dropped_count\": 0, \n" + "      \"issue_open_count\": 0, \n"
        + "      \"issue_resolved_count\": 0, \n" + "      \"last_updated\": \"2007-06-24T00:28:33Z\", \n"
        + "      \"links\": {\n" + "        \"changes\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/3/changes/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"delete\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/3/\", \n"
        + "          \"method\": \"DELETE\"\n" + "        }, \n" + "        \"diff_context\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/3/diff-context/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"diffs\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/3/diffs/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"draft\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/3/draft/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"file_attachments\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/3/file-attachments/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"last_update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/3/last-update/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"latest_diff\": {\n"
        + "          \"href\": \"http://example.com/api/review-requests/3/diffs/1/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"repository\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"Review Board SVN\"\n" + "        }, \n"
        + "        \"reviews\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/3/reviews/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"screenshots\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/3/screenshots/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/3/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"status_updates\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/3/status-updates/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"submitter\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/users/admin/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"admin\"\n" + "        }, \n"
        + "        \"update\": {\n" + "          \"href\": \"http://reviews.example.com/api/review-requests/3/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }\n" + "      }, \n" + "      \"public\": true, \n"
        + "      \"ship_it_count\": 0, \n" + "      \"status\": \"pending\", \n"
        + "      \"summary\": \"Add permission checking for JSON API\", \n" + "      \"target_groups\": [\n"
        + "        {\n" + "          \"href\": \"http://reviews.example.com/api/groups/privgroup/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"privgroup\"\n" + "        }\n" + "      ], \n"
        + "      \"target_people\": [\n" + "        {\n"
        + "          \"href\": \"http://reviews.example.com/api/users/doc/\", \n" + "          \"method\": \"GET\", \n"
        + "          \"title\": \"doc\"\n" + "        }, \n" + "        {\n"
        + "          \"href\": \"http://reviews.example.com/api/users/dopey/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"dopey\"\n" + "        }\n" + "      ], \n"
        + "      \"testing_done\": \"Tested some functions.\", \n" + "      \"testing_done_text_type\": \"plain\", \n"
        + "      \"text_type\": null, \n" + "      \"time_added\": \"2007-06-24T00:17:33Z\", \n"
        + "      \"url\": \"/r/3/\"\n" + "    }\n" + "  ], \n" + "  \"stat\": \"ok\", \n" + "  \"total_results\": 6\n"
        + "}";
    ReviewRequests collection = new Gson().fromJson(response, ReviewRequests.class);
    System.out.println(collection);
  }

  private static void testRepositories() {
    String response = "{\n" + "  \"links\": {\n" + "    \"create\": {\n"
        + "      \"href\": \"http://reviews.example.com/api/repositories/\", \n" + "      \"method\": \"POST\"\n"
        + "    }, \n" + "    \"self\": {\n" + "      \"href\": \"http://reviews.example.com/api/repositories/\", \n"
        + "      \"method\": \"GET\"\n" + "    }\n" + "  }, \n" + "  \"repositories\": [\n" + "    {\n"
        + "      \"bug_tracker\": \"http://code.google.com/p/reviewboard/issues/detail?id=%s\", \n"
        + "      \"id\": 1, \n" + "      \"links\": {\n" + "        \"branches\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/branches/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"commits\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/commits/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"delete\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/\", \n"
        + "          \"method\": \"DELETE\"\n" + "        }, \n" + "        \"diff_file_attachments\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/diff-file-attachments/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"info\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/info/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/1/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }\n" + "      }, \n" + "      \"mirror_path\": \"\", \n"
        + "      \"name\": \"Review Board SVN\", \n" + "      \"path\": \"https://svn.riouxsvn.com/reviewboard/\", \n"
        + "      \"tool\": \"Subversion\", \n" + "      \"visible\": true\n" + "    }, \n" + "    {\n"
        + "      \"bug_tracker\": \"\", \n" + "      \"id\": 2, \n" + "      \"links\": {\n"
        + "        \"branches\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/2/branches/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"commits\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/2/commits/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"delete\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/2/\", \n"
        + "          \"method\": \"DELETE\"\n" + "        }, \n" + "        \"diff_file_attachments\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/2/diff-file-attachments/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"info\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/2/info/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/2/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/repositories/2/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }\n" + "      }, \n" + "      \"mirror_path\": \"\", \n"
        + "      \"name\": \"Navi SVN\", \n" + "      \"path\": \"http://svn.navi.cx/misc\", \n"
        + "      \"tool\": \"Subversion\", \n" + "      \"visible\": true\n" + "    }\n" + "  ], \n"
        + "  \"stat\": \"ok\", \n" + "  \"total_results\": 2\n" + "}";

    Repositories repositories = null;
    try {
      repositories = new Gson().fromJson(new InputStreamReader(Test.class.getResourceAsStream("repositories.json")), Repositories.class);
    } catch (Exception e) {
      e.printStackTrace();
    }
    System.out.println(repositories);
  }

  private static void testComments() {
    String response = "{\n" + "  \"diff_comments\": [\n" + "    {\n" + "      \"extra_data\": {}, \n"
        + "      \"first_line\": 12, \n" + "      \"id\": 5, \n" + "      \"interfilediff\": null, \n"
        + "      \"issue_opened\": false, \n" + "      \"issue_status\": \"\", \n" + "      \"links\": {\n"
        + "        \"delete\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/reviews/8/diff-comments/5/\", \n"
        + "          \"method\": \"DELETE\"\n" + "        }, \n" + "        \"filediff\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/3/files/41/\", \n"
        + "          \"method\": \"GET\", \n"
        + "          \"title\": \"/trunk/reviewboard/settings_local.py.tmpl (1797) -> /trunk/reviewboard/settings_local.py.tmpl ((working copy))\"\n"
        + "        }, \n" + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/reviews/8/diff-comments/5/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/reviews/8/diff-comments/5/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }, \n" + "        \"user\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/users/admin/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"admin\"\n" + "        }\n" + "      }, \n"
        + "      \"num_lines\": 3, \n" + "      \"public\": true, \n"
        + "      \"text\": \"This is just a sample comment.\", \n" + "      \"text_type\": \"plain\", \n"
        + "      \"timestamp\": \"2010-08-22T17:25:41Z\"\n" + "    }, \n" + "    {\n" + "      \"extra_data\": {}, \n"
        + "      \"first_line\": 29, \n" + "      \"id\": 6, \n" + "      \"interfilediff\": null, \n"
        + "      \"issue_opened\": false, \n" + "      \"issue_status\": \"\", \n" + "      \"links\": {\n"
        + "        \"delete\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/reviews/8/diff-comments/6/\", \n"
        + "          \"method\": \"DELETE\"\n" + "        }, \n" + "        \"filediff\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/diffs/3/files/41/\", \n"
        + "          \"method\": \"GET\", \n"
        + "          \"title\": \"/trunk/reviewboard/settings_local.py.tmpl (1797) -> /trunk/reviewboard/settings_local.py.tmpl ((working copy))\"\n"
        + "        }, \n" + "        \"self\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/reviews/8/diff-comments/6/\", \n"
        + "          \"method\": \"GET\"\n" + "        }, \n" + "        \"update\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/review-requests/8/reviews/8/diff-comments/6/\", \n"
        + "          \"method\": \"PUT\"\n" + "        }, \n" + "        \"user\": {\n"
        + "          \"href\": \"http://reviews.example.com/api/users/admin/\", \n"
        + "          \"method\": \"GET\", \n" + "          \"title\": \"admin\"\n" + "        }\n" + "      }, \n"
        + "      \"num_lines\": 3, \n" + "      \"public\": true, \n"
        + "      \"text\": \"Another sample comment.\", \n" + "      \"text_type\": \"plain\", \n"
        + "      \"timestamp\": \"2010-08-22T17:25:52Z\"\n" + "    }\n" + "  ], \n" + "  \"links\": {\n"
        + "    \"create\": {\n"
        + "      \"href\": \"http://reviews.example.com/api/review-requests/8/reviews/8/diff-comments/\", \n"
        + "      \"method\": \"POST\"\n" + "    }, \n" + "    \"self\": {\n"
        + "      \"href\": \"http://reviews.example.com/api/review-requests/8/reviews/8/diff-comments/\", \n"
        + "      \"method\": \"GET\"\n" + "    }\n" + "  }, \n" + "  \"stat\": \"ok\", \n" + "  \"total_results\": 2\n"
        + "}";
    Comments comments = new Gson().fromJson(response, Comments.class);
    System.out.println(comments);
  }
}

